include: package:lint/analysis_options.yaml

analyzer:
  exclude: [
    # 'lib/*.config.dart',
    'lib/*.g.dart',
    'lib/generated/**/*.dart'
    ]

linter:
  rules:
    sort_pub_dependecies: none
    invalid_use_of_protected_member: error

