name: producti
description: Upgraded todo app project!
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # UI
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0

  # Firebase
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  firebase_crashlytics: ^2.2.0
  
  
  # State management
  bloc: ^7.1.0
  flutter_bloc: ^7.1.0
  hydrated_bloc: ^7.0.1
  get: ^4.3.8
  
  # DI
  injectable: ^1.5.0
  get_it: ^7.2.0
  

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.1
  build_runner: ^2.1.1
  
  lint: ^1.6.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
