name: producti
description: Upgraded todo app project!
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Connectivity check
  connectivity: ^3.0.6

  # UI
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  producti_ui:
    path: ./producti_ui/
  simple_animations: ^4.0.0
  
  # Firebase
  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  firebase_crashlytics: ^2.2.0
  firebase_analytics: ^8.3.0

  # State management
  bloc: ^7.1.0
  flutter_bloc: ^7.1.0
  hydrated_bloc: ^7.0.1

  # Dart features
  equatable: ^2.0.3
  dartz: ^0.10.0
  logger: ^1.1.0
  
  # DI
  injectable: ^1.5.0
  get_it: ^7.2.0

  # Flutter project settings
  path_provider: ^2.0.3

  # Storages
  flutter_secure_storage: ^4.2.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.1
  build_runner: ^2.1.1
  hive_generator: ^1.1.1

  lint: ^1.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
