name: producti
description: Upgraded todo app project!
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.1.1"

dependencies:
  # Notifications
  flutter_local_notifications: ^9.0.2
  flutter_native_timezone: ^2.0.0

  # URL
  url_launcher: ^6.0.12

  # Connectivity check
  connectivity: ^3.0.6

  # UI
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_fonts: ^5.1.0
  intl: ^0.18.0
  producti_ui:
    path: ./producti_ui/
  simple_animations: ^5.0.2
  showcaseview: ^2.0.3
  flutter_reorderable_list: ^1.1.0
  flutter_slidable: ^3.0.0
  flutter_switch: ^0.3.2
  flutter_screenutil: ^5.0.0+2
    
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_crashlytics: ^3.3.5
  firebase_analytics: ^10.4.5

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2

  # Dart features
  equatable: ^2.0.3
  dartz: ^0.10.0
  logger: ^2.0.2
  rxdart: ^0.27.3
  
  # DI
  injectable: ^2.3.0
  get_it: ^7.2.0

  # Flutter project settings
  path_provider: ^2.0.3

  # Storages
  flutter_secure_storage: ^9.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  build_runner: ^2.1.1
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
